---
title: "Singular Value Decomposition"
author: "Alexander Alexandrov"
date: "Thursday, October 22, 2015"
output: pdf_document
---

# Singular Value Decomposition

```{r}
set.seed(12345)
dataMatrix <- matrix(rnorm(400), nrow = 40)
image(1:10, 1:40, t(dataMatrix))
```

```{r}
heatmap(dataMatrix)
```

\newpage

```{r}
for (i in 1:40) {
    coinFlip <- rbinom(1, size = 1, prob = 0.5)
    if (coinFlip) {
        dataMatrix[i, ] <- dataMatrix[i, ] + rep(c(0, 3), each = 5)
    }
}
image(1:10, 1:40, t(dataMatrix))
```

```{r}
heatmap(dataMatrix)
```

\newpage

```{r}
dataMatrixOrdered <- dataMatrix[hclust(dist(dataMatrix))$order, ]

par(mfrow = c(1, 3))
image(1:10, 1:40, t(dataMatrixOrdered))
plot(rowMeans(dataMatrixOrdered), xlab = "Row Mean", pch = 19)
plot(colMeans(dataMatrixOrdered), xlab = "Col Mean", pch = 19)
```

\newpage

```{r}
decomposedData <- svd(scale(dataMatrixOrdered))

par(mfrow = c(1, 3))
image(1:10, 1:40, t(dataMatrixOrdered))
plot(decomposedData$u[, 1], xlab = "First left singular vector", pch = 19)
plot(decomposedData$v[, 1], xlab = "First right singular vector", pch = 19)
```

\newpage

```{r}
par(mfrow = c(1, 2))
plot(decomposedData$d, xlab = "Column", ylab = "Singular value", pch = 19)
plot(decomposedData$d^2 / sum(decomposedData$d^2), xlab = "Column", ylab = "Variance explained", pch = 19)
```

\newpage

```{r}
simpleMatrix <- matrix(rep(rep(c(0, 1), each = 5), each = 10), nrow = 10)
decomposedSimpleMatrix <- svd(simpleMatrix)

par(mfrow = c(1, 2))
image(t(simpleMatrix))
plot(decomposedSimpleMatrix$d, xlab = "Column", ylab = "Singular value", pch = 19)
```
